### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by smramgator** [graham-walker/youtube-dl-react-viewer#26]
Hi!  Is there a way to undo everything that the install.bat performed, i.e. an uninstall ability?

**Comment by graham-walker** [comment]
install.bat only installs the package's node modules.

The only thing you need to remove after running install.bat is PM2 (since it is installed globally), which you can uninstall by opening the terminal and running `npm remove pm2 -g`.

Additionally, for Linux users who used install.sh, it also installs xattr, which you can uninstall. However, note that xattr might have already been installed on your system by default and you might not want to remove it.
