### ISSUE TITLE
Dollar Sign in Video Title not handled correctly

### ISSUE THREAD

**Issue by dyslexicjedi** [graham-walker/youtube-dl-react-viewer#5]
Error output on frontend

`{
    "stack": "Error: ENOENT: no such file or directory, stat '/data/videos/youtube/esb-rdjGKeM/LIVING IN CHIANG MAI _  Apartment Tour & Thailand Tourist Visa Extension - Kara and Nate - 20181217.mkv'
    at Object.statSync (node:fs:1121:3)
    at Object.statSync (/opt/youtube-dl-react-viewer/youtube-dl-express-backend/node_modules/graceful-fs/polyfills.js:308:16)
    at file:///opt/youtube-dl-react-viewer/youtube-dl-express-backend/exec.js:66:26
    at processTicksAndRejections (node:internal/process/task_queues:93:5)",
    "message": "ENOENT: no such file or directory, stat '/data/videos/youtube/esb-rdjGKeM/LIVING IN CHIANG MAI _  Apartment Tour & Thailand Tourist Visa Extension - Kara and Nate - 20181217.mkv'",
    "errno": -2,
    "syscall": "stat",
    "code": "ENOENT",
    "path": "/data/videos/youtube/esb-rdjGKeM/LIVING IN CHIANG MAI _  Apartment Tour & Thailand Tourist Visa Extension - Kara and Nate - 20181217.mkv"
}`

Found on the backend

`-rw-r--r-- 1 root root 3.1K Nov 27 15:48 LIVING\ IN\ CHIANG\ MAI\ _\ $750\ Apartment\ Tour\ &\ Thailand\ Tourist\ Visa\ Extension\ -\ Kara\ and\ Nate\ -\ 20181217.description
-rw-r--r-- 1 root root  44K Nov 27 15:48 LIVING\ IN\ CHIANG\ MAI\ _\ $750\ Apartment\ Tour\ &\ Thailand\ Tourist\ Visa\ Extension\ -\ Kara\ and\ Nate\ -\ 20181217.info.json
-rw-r--r-- 1 root root 197M Dec 18  2018 LIVING\ IN\ CHIANG\ MAI\ _\ $750\ Apartment\ Tour\ &\ Thailand\ Tourist\ Visa\ Extension\ -\ Kara\ and\ Nate\ -\ 20181217.mkv
-rw-r--r-- 1 root root 6.8K Nov 27 15:48 LIVING\ IN\ CHIANG\ MAI\ _\ $750\ Apartment\ Tour\ &\ Thailand\ Tourist\ Visa\ Extension\ -\ Kara\ and\ Nate\ -\ 20181217_0.jpg
-rw-r--r-- 1 root root 8.6K Nov 27 15:48 LIVING\ IN\ CHIANG\ MAI\ _\ $750\ Apartment\ Tour\ &\ Thailand\ Tourist\ Visa\ Extension\ -\ Kara\ and\ Nate\ -\ 20181217_1.jpg
-rw-r--r-- 1 root root  12K Nov 27 15:48 LIVING\ IN\ CHIANG\ MAI\ _\ $750\ Apartment\ Tour\ &\ Thailand\ Tourist\ Visa\ Extension\ -\ Kara\ and\ Nate\ -\ 20181217_2.jpg
-rw-r--r-- 1 root root  19K Nov 27 15:48 LIVING\ IN\ CHIANG\ MAI\ _\ $750\ Apartment\ Tour\ &\ Thailand\ Tourist\ Visa\ Extension\ -\ Kara\ and\ Nate\ -\ 20181217_3.jpg
-rw-r--r-- 1 root root  91K Nov 27 15:48 LIVING\ IN\ CHIANG\ MAI\ _\ $750\ Apartment\ Tour\ &\ Thailand\ Tourist\ Visa\ Extension\ -\ Kara\ and\ Nate\ -\ 20181217_4.webp
`

Looks like the $750 is being dropped somewhere

**Comment by JamoDevNich** [comment]
Done a little digging and think I see what's going on here. `npm run exec` appears to be replacing single quotes in the parameters with double quotes

1. Youtube-dl completes the download successfully, then executes [`npm run exec`](https://github.com/graham-walker/youtube-dl-react-viewer/blob/7401cd81cb4eebd40fb5d88b3966a595ca9665b3/youtube-dl-express-backend/utilities/job.utility.js#L56-L57) with the video title wrapped in single quotes

2. `npm run exec` then runs [`node --require dotenv/config exec.js`](https://github.com/graham-walker/youtube-dl-react-viewer/blob/7401cd81cb4eebd40fb5d88b3966a595ca9665b3/youtube-dl-express-backend/package.json#L9), but replaces the single quotes with double quotes. This would cause the shell to expand the `$750` in the video title.

3. The `$750` is expanded to *nothing* because it has no value set, leaving a blank space in the video title. [exec.js](https://github.com/graham-walker/youtube-dl-react-viewer/blob/7401cd81cb4eebd40fb5d88b3966a595ca9665b3/youtube-dl-express-backend/exec.js#L74) rightfully fails to locate the video file.

This might not affect command prompt/cmd on Windows as that uses percent `%` for variables, not sure about PowerShell.

**Log**:
```
app_1  | [ffmpeg] Adding metadata to '/youtube-dl/videos/youtube/esb-rdjGKeM/LIVING IN CHIANG MAI _ $750 Apartment Tour & Thailand Tourist Visa Extension - Kara and Nate - 20181217.mp4'
app_1  | [metadata] Writing metadata to file's xattrs
app_1  | [exec] Executing command: npm run exec -- --youtube-dl-version 2020.11.11-3 --job-id 5fc1ecd16be8e60007b27c71 --video '/youtube-dl/videos/youtube/esb-rdjGKeM/LIVING IN CHIANG MAI _ $750 Apartment Tour & Thailand Tourist Visa Extension - Kara and Nate - 20181217.mp4'
app_1  |
app_1  | > youtube-dl-express-backend@1.1.1 exec
app_1  | > node --require dotenv/config exec.js "--youtube-dl-version" "2020.11.11-3" "--job-id" "5fc1ecd16be8e60007b27c71" "--video" "/youtube-dl/videos/youtube/esb-rdjGKeM/LIVING IN CHIANG MAI _ $750 Apartment Tour & Thailand Tourist Visa Extension - Kara and Nate - 20181217.mp4"
app_1  |
app_1  | === Dumping arguments ===
app_1  | [
app_1  |   '/usr/local/bin/node',
app_1  |   '/opt/youtube-dl-react-viewer/youtube-dl-express-backend/exec.js',
app_1  |   '--youtube-dl-version',
app_1  |   '2020.11.11-3',
app_1  |   '--job-id',
app_1  |   '5fc1ecd16be8e60007b27c71',
app_1  |   '--video',
app_1  |   '/youtube-dl/videos/youtube/esb-rdjGKeM/LIVING IN CHIANG MAI _  Apartment Tour & Thailand Tourist Visa Extension - Kara and Nate - 20181217.mp4'
app_1  | ]
app_1  | Perparing to insert document for video: /youtube-dl/videos/youtube/esb-rdjGKeM/LIVING IN CHIANG MAI _  Apartment Tour & Thailand Tourist Visa Extension - Kara and Nate - 20181217.mp4 into the database
```

**Comment by JamoDevNich** [comment]
I've had a very brief look at some of the ways this could be fixed or worked around, it could also possibly affect importing videos with dollar signs in the title.

1. Force npm to keep the single quotes - not sure if this is possible?
    [StackOverflow post](https://stackoverflow.com/a/37501023/2422168) mentioning a similar situation
    [Issue on npm-scripts](https://github.com/keithamus/npm-scripts-example/issues/5) mentioning a similar situation

2. Changing the script from `npm run exec` => `node --require dotenv/config /opt/youtube-dl-react-viewer/youtube-dl-express-backend/exec.js` - not ideal but possible
    The exec script seems to require environment variables set by `npm`. Module `dotenv/config` also might be unable to load the .env, depending on the working directory

3. Escape the dollar sign
    For [imports](https://github.com/graham-walker/youtube-dl-react-viewer/blob/5fdde8b1fa6b1fb5002638dabd567b7698a83e21/youtube-dl-express-backend/import.js#L178-L189) this should be possible with the [shell-escape](https://www.npmjs.com/package/shell-escape#example) package.
    For youtube-dl's exec this would be hacky. They call [compat_shlex_quote](https://github.com/ytdl-org/youtube-dl/blob/20c50c65566be31607e59d7ca2467c664a29c843/youtube_dl/compat.py#L2647-L2658) on the video filename which applies quotes to the output filename based on the OS. Since this likely just affects Unix shells it might be possible to have  youtube-dl call a script which escapes the dollar sign (if the OS is unix-based), and pass the escaped parameters to npm.

**Comment by dyslexicjedi** [comment]
So I tried the new 1.2.1 version, the docker log shows the file downloaded. 
`[download] Downloading video 4 of 759
[download] WE SLEPT 220 FEET BELOW GROUND (worth $1,000 per night?) has already been recorded in archive`

But if I search for "WE SLEPT 220 FEET" in the web frontend, I get no results.

**Comment by JamoDevNich** [comment]
I tried to repro this on my system but the video showed up in the search just fine, so I think you could be right about the videos being already downloaded but not added. There's a couple things you could try:

- **Repairing the job**: I'm not too familiar with this myself as I've never had to use it, see if repairing the job from the admin panel sorts it out

- **Importing the video**: Move the `/youtube-dl/videos/youtube/0iJuNhs9Abc` folder to another location, and [import it](https://github.com/graham-walker/youtube-dl-react-viewer#importing-already-downloaded-videos)

-  **Manually adding the video**: For this you'll need the job ID. You can get it from the logs by downloading another video in the same job, and searching the logs for `--job-id`. Then you can run a command such as this in the container:
    ```
    node --require dotenv/config exec.js --job-id JOB_ID_HERE --video '/youtube-dl/videos/youtube/0iJuNhs9Abc/WE SLEPT 220 FEET BELOW GROUND (worth $1,000 per night) - Kara and Nate - 20201129.mkv'
    ```
    and replace *JOB_ID_HERE* in the command with the job ID.

- **Re-downloading the video**: Remove the line containing _0iJuNhs9Abc_ from the `/youtube-dl/archive.txt` file, delete the `/youtube-dl/videos/youtube/0iJuNhs9Abc` folder, and run the job again to re-download the video
  
  
If you've got a lot of these videos with dollar signs, you can find them by running the command `find /youtube-dl -name '*$*.mp4' -o -name '*$*.mkv'` inside the container. In such a case, it may be a better idea to repair or re-download the videos, since they are already associated with the correct job

**Comment by graham-walker** [comment]
> So I tried the new 1.2.1 version, the docker log shows the file downloaded.
> `[download] Downloading video 4 of 759 [download] WE SLEPT 220 FEET BELOW GROUND (worth $1,000 per night?) has already been recorded in archive`
> 
> But if I search for "WE SLEPT 220 FEET" in the web frontend, I get no results.
> 
> edit: I'm wondering if I need to somehow clear the video and redownload/import it to get it to show up now. Since it downloaded but didn't get added in the previous version. But I've got like 2.5 TB so I'd have to write something to find anything with a $ sign, I wouldn't want to do everything.

This is happening because the error that prevented the video from being added to the app's database occurs after youtube-dl has successfully downloaded the video. As such the video is already present in the filesystem and in `archive.txt`, so it will not be downloaded again if you re-run the job.

Errors like this one should get recorded and appear in a list on the admin panel of the app. Normally to automatically fix these errors you would select an error from the list by clicking "Show Details" and then "Attempt Repair". However, this specific error occurred because the "$" character was being erroneously escaped when youtube-dl passed the video path to the app. This means that clicking "Attempt Repair" will fail because the path that the error has recorded does not point to an existing video file. Fortunately, there is an easy fix if you are willing to edit the database:

1. Update the app to the version 1.2.1
2. Identify the error you want to repair from the admin panel and copy the path that appears above "Show Details". It will look something like: "Extractor/Video Id/Video Title - Uploader Name - Date Uploaded.mkv"
2. Open the database in whichever program you are most comfortable with
3. Select the `errors` table
4. Find the error you want to repair by filtering `{videoPath: 'The path you copied in step 2'}`
5. Change the value of `videoPath` so it points to the correct filename and save
6. Go back to error in the admin panel and click "Attempt Repair"

If you are fine with redownloading the video you can also do what @JamoDevNich suggests and delete the video id from `archive.txt` and run the job again. This however, will not remove the recorded error in the admin panel and you will have to delete it from the database manually.

**Comment by dyslexicjedi** [comment]
I tried a test by removing one of the id's from the archive.txt and it imported it successfully. So I wrote this quick one liner to fix the issue.
`find videos/ -name '*$*.mp4' -o -name '*$*.mkv' | cut -d/ -f3 | xargs -I '{}' sed -i '/{}/d' archive.txt`

The videos are reimporting now. Thanks!!!
